name: app_food_2023
description: A Flutter project of Food Delivery
version: 0.1.1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  
  firebase_core: ^3.1.0
  pinput: ^2.2.31
  firebase_auth: ^5.1.0
  firebase_storage: ^12.0.1
  image_picker: ^1.1.2
  fluttertoast: ^8.2.1
  cloud_firestore: ^5.0.1
  shared_preferences: ^2.2.3
  google_fonts: ^6.2.1
  # js_bindings: ^0.1.2+1
  flutter_svg: ^2.0.5
  cached_network_image: ^3.3.1 
  google_sign_in: ^6.2.1
  # getwidget: ^3.1.1
  # firebase_admin: ^0.2.0
  # font_awesome_flutter: ^10.4.0
  # flutter_spinkit: ^5.1.0
  flutter_rating_bar: ^4.0.1
  geolocator: ^10.0.1
  cupertino_icons: ^1.0.8
  google_api_headers: ^2.0.0
  google_maps_flutter: ^2.7.0
  flutter_google_maps_webservices: ^1.1.1
  flutter_staggered_grid_view: ^0.4.0
  google_maps_place_picker_mb: ^3.1.2 
  provider: ^6.0.5
  tuple: ^2.0.1
  get: ^4.6.6
  uuid: ^4.4.0 
  image_cropper: ^7.0.5
  geocoding: ^2.1.0
  scroll_edge_listener: ^0.1.1
  introduction_screen: ^3.1.8
  intl: ^0.19.0
  lottie: ^2.3.2
  logger: ^2.3.0




dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - images/userAvatar/
  - images/
  - assets/
  - assets/gifs/
  - assets/images/
  - assets/icon/
