// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsEV-_L3qKEhBYnMnqz7LQUKDQpE5_qhI',
    appId: '1:389613032858:android:dc43b249188ee2a7ba1623',
    messagingSenderId: '389613032858',
    projectId: 'fir-v1-3a26a',
    databaseURL: 'https://fir-v1-3a26a-default-rtdb.firebaseio.com',
    storageBucket: 'fir-v1-3a26a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgLmWKqpoAz2H8ilvSrlZgc2I83oz3Rm0',
    appId: '1:389613032858:ios:7d7e3651f054a3b1ba1623',
    messagingSenderId: '389613032858',
    projectId: 'fir-v1-3a26a',
    databaseURL: 'https://fir-v1-3a26a-default-rtdb.firebaseio.com',
    storageBucket: 'fir-v1-3a26a.appspot.com',
    androidClientId: '389613032858-bmlq2mpiei1t8kguskf5hlpp313e0h6j.apps.googleusercontent.com',
    iosClientId: '389613032858-6s02v797uj4u68739573gnnstlc8paij.apps.googleusercontent.com',
    iosBundleId: 'com.example.appFoodDelivery',
  );
}
